[project]
name = "telemedicine-platform"
description = "A decentralized telemedicine platform connecting rural patients with urban medical professionals"
authors = []
telemetry = false
requirements = []

[contracts.consultation]
path = "contracts/consultation.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
